### ISSUE TITLE
Typo in type name `OtherVATableTaxBaseType`

### ISSUE THREAD

**Issue by phax** [austriapro/ebinterface-standards#12]
Hier fehlt ein `t` - es sollte `OtherVATTableTaxBaseType` heißen :)

**Comment by phax** [comment]
Das gilt auch für `OtherVATableTaxType`

**Comment by paundl** [comment]
Hi Philip,
Danke für den Hinweis, werde ich ausbessern.
LG, Paul

Am 18.10.2016 8:44 Vorm. schrieb "Philip Helger" <notifications@github.com>:

Hier fehlt ein t - es sollte OtherVATTableTaxBaseType heißen :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/austriapro/ebinterface-standards/issues/12>, or mute
the thread

**Comment by phax** [comment]
Nein vergiss es.
Es soll heißen "stauerbar" - "VATable"
